# Generated by Django 2.0.2 on 2018-04-18 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nullhydfollower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nullhydfollower',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
