# Generated by Django 2.0.2 on 2018-04-19 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180419_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nullhydfollower',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='nullhydfollower',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
